FROM golang:latest
LABEL lzyyauto "lzyyauto@gmail.com"
RUN mkdir -p /auto4play
WORKDIR /auto4play

ADD . /auto4play
ADD ./config/config.json /auto4play/config

RUN go build .

EXPOSE 8000

CMD ["./auto4play"]